version: '3'
services:
  backendflask:
    build:
      context: ./backendflask
      dockerfile: ./Dockerfile
    environment:
    - HELLO_SERVICE_PORT=80
    deploy:
      replicas: 1
    expose:
    - 80
  frontendflask:
    build:
      context: ./frontendflask
      dockerfile: ./Dockerfile
    ports:
      - 80:8090
    environment:
    - PORT=8090
    - HELLO_SERVICE_HOST_PREFIX=https://backendflask.internal
    depends_on:
      - backendflask
    deploy:
      replicas: 1
